{
    "info" : "Running mvn gcloud:run...",
    "cmd" : [
      "mvn-c9.sh",
      "--threads=4", "-DskipTests=true", "-DskipTests=true", "-Dmaven.test.skip=true", "-Darguments='-DskipTests'",
      "clean",
      "com.google.appengine:gcloud-maven-plugin::run", "-Dgcloud.host=$IP:$PORT"
    ],
    "working_dir": "$project_path",
    "env" : {
      "JAVA_HOME": "/usr/lib/jvm/java-8-oracle",
      "MAVEN_OPTS": "'-XX:+TieredCompilation -XX:TieredStopAtLevel=1 -Xms32m'"
    }
}
