{
    "info" : "Running mvn gcloud:deploy...",
    "cmd" : [
      "mvn",
      "--threads=4", "-DskipTests=true", "-DskipTests=true", "-Dmaven.test.skip=true", "-Darguments=-DskipTests", "-Doverride.build.directory=target-deploy",
      "clean", "gcloud:deploy", "clean"
    ],
    "working_dir": "$project_path",
    "env" : {
      "JAVA_HOME": "/usr/lib/jvm/java-8-oracle",
      "MAVEN_OPTS": "'-Xms32m'"
    }
}
