{
    "info" : "Running mvn gcloud:run and watching for changes...",
    "cmd" : [
      "mvn",
      "--threads=4", "-DskipTests=true", "-DskipTests=true", "-Dmaven.test.skip=true", "-Darguments=-DskipTests", "-Dgcloud.host=$IP:$PORT",
      "clean", "gcloud:run_start", "fizzed-watcher:run"
    ],
    "working_dir": "$project_path",
    "env" : {
      "JAVA_HOME": "/usr/lib/jvm/java-8-oracle",
      "MAVEN_OPTS": "'-XX:+TieredCompilation -XX:TieredStopAtLevel=1 -Xms32m'"
    }
}
